name: Build and deploy system

on:
  push:
    branches: 
      - "deploy"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build . -t movinsilva/travelgo-frontend:latest

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: docker push movinsilva/travelgo-frontend:latest
      
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: stop current container
      run: echo "root123" | sudo -S sudo docker stop travelgo-frontend-container || true
    - name: remove current container
      run: echo "root123" | sudo -S sudo docker rm travelgo-frontend-container || true
    - name: remove current image
      run: echo "root123" | sudo -S sudo docker rmi movinsilva/travelgo-frontend:latest -f || true
    - name: pull new image
      run: echo "root123" | sudo -S sudo docker pull movinsilva/travelgo-frontend:latest
    - name: run new container
      run: echo "root123" | sudo -S sudo docker run -p 13000:13000 -d --name travelgo-frontend-container  movinsilva/travelgo-frontend:latest